title: AGL
description: >- 
  Economics student interested in Econometrics, 
  Statistics, Actuarial sciences, and Economic research.
baseurl: ""
author: André-Ignace Ghonda Lukoki
show_author: true
collections:
  blog:
    output: true
    permalink: /blog/:year/:title.html
  projects:
    output: true
    permalink: /code/:title.html


kramdown:
  math_engine: katex
  syntax_highlighter: rouge
url: "https://andreghonda.com" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-tufte
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag