title: AGL
description: >- 
  Econometrics and Operations research student
  interested in Game Theory, Optimization, and Data.
url: "https://andreghonda.com" # the base hostname & protocol for your site
baseurl: ""
author: André-Ignace Ghonda Lukoki
show_author: true
collections:
  blog:
    output: true
    permalink: /blog/:year/:title.html
  projects:
    output: true
    permalink: /code/:title.html

kramdown:
  math_engine: katex
  syntax_highlighter: rouge
  math_engine_opts:
    katex:
      delimiters:
        - ['$$', '$$']
        - ['$', '$']

# Build settings
theme: jekyll-theme-tufte
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag