title: AGL
description: >- 
  Economics student interested in Econometrics, 
  Statistics, Actuarial sciences, and Economic research.
baseurl: ""
author: André
show_author: true
permalink: /blog/:year/:title.html
markdown: kramdown

# Build settings
theme: jekyll-theme-tufte
plugins:
  - jekyll-feed
